name: Generate Lineups

on:
  schedule:
    - cron: '0 12 * * *' # Run every day at 12pm UTC
  workflow_dispatch: # Triggered manually

jobs:
  generate-lineups:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn ortools
        pip install -r requirements.txt
        pip install openai  # Add this line to install the openai package

    - name: Generate lineups
      run: |
        python main.py
